language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t powerjms0324/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true powerjms0324/react-test-app npm run test

after_success:
  - docker build -t powerjms0324/docker-frontend ./frontend
  - docker build -t powerjms0324/docker-backend ./backend
  - docker build -t powerjms0324/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push powerjms0324/docker-frontend
  - docker push powerjms0324/docker-backend
  - docker push powerjms0324/docker-nginx

notifications:
  email:
    recipients:
      - msjang@bellock.co.kr
