version: "3"
services:
  frontend:
    image: powerjms0324/docker-frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    mem_limit: 128m

  nginx: 
    restart: always
    image: powerjms0324/docker-nginx
    ports: 
      - "80:80"

  backend:
    image: powerjms0324/docker-backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    mem_limit: 128m
    environment: 
      MYSQL_HOST: root 
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: johnahn777
      MYSQL_DATABASE: myapp
      MYSQL_PORT: 3306
    mem_limit: 128m   
